-- Active: 1763694043295@@ora-dwhdb-pri.centralretail.com.vn@1521@DWHDB@OMNI_DIGIMGR
--@@ Input & Output: OMNI_DIGIMGR.LOUTRUONG_DIM_SUPPLIER
--@@ Input & Output: OMNI_DIGIMGR.LOUTRUONG_DIM_SUPPLIER_OFFLINE
--@@ Input: OMNI_DIGIMGR.LOUTRUONG_SUPPLIER_PERF_DI
--@@ Input: OMNI_DIGIMGR.LOUTRUONG_SUPPLIER_BYR_PERF_DI
-- Create the dim table for all team use
-- DROP TABLE OMNI_DIGIMGR.LOUTRUONG_DIM_SUPPLIER
-- ;
-- CREATE TABLE
-- 	OMNI_DIGIMGR.LOUTRUONG_DIM_SUPPLIER (supplier_group VARCHAR2 (100) NOT NULL, supplier_code VARCHAR2 (100) NOT NULL, supplier_name VARCHAR2 (100), is_bi_use NUMBER (1) DEFAULT 0 NOT NULL CHECK (is_bi_use IN (0, 1)), ds DATE NOT NULL, CONSTRAINT PK_LOUTRUONG_DIM_SUPPLIER PRIMARY KEY (supplier_code))
-- ;
-- DROP TABLE OMNI_DIGIMGR.LOUTRUONG_DIM_SUPPLIER_OFFLINE
-- ;
-- CREATE TABLE
-- 	OMNI_DIGIMGR.LOUTRUONG_DIM_SUPPLIER_OFFLINE (product_code VARCHAR2 (100) NOT NULL, supplier_code_omni VARCHAR2 (100) NOT NULL, supplier_code_omni_map VARCHAR2 (100) NOT NULL, supplier_name VARCHAR2 (100), ds DATE NOT NULL, CONSTRAINT PK_LOUTRUONG_DIM_SUPPLIER_OFFLINE PRIMARY KEY (PRODUCT_CODE))
-- ;
SELECT
	*
FROM
	crv_data.LOUTRUONG_SUPPLIER_PERF_DI
WHERE
	1 = 1
	AND (SALE_DATE BETWEEN '29-MAR-2026' AND '29-MAR-2026')
	AND SUPPLIER_CODE IN ('00_all_hyper')
	-- AND DIMENSION_GROUP IN ('channel')
	-- AND SUPPLIER_CODE IS NULL
	-- AND LOWER(SUPPLIER_CODE) IN ('00_all_omni')
	-- AND LOWER(DIMENSION) IN ('omni')
;